### ISSUE TITLE
Would you please provide your reproduced results on DAIR-V2X-C of HEAL with spconv 2.x ?

### ISSUE THREAD

**Issue by ChengchangTian** [Chinese-Coding/ClosedHEAL#1]
I am very grateful for your work on the reproduction and improvement of HEAL under the spconv2.x configuration. I have also reproduced HEAL on the DAIR-V2X-C dataset under the spconv 2.x environment, using LiDAR point cloud data. The results for the M1 phase are as follows:

ap30: 0.7972982399281199
ap_50: 0.751092880923946
ap_70: 0.5888742505287062

, which shows some discrepancy compared to the results recorded in the paper. I would like to know how your reproduction results for this dataset are, and I am looking forward to your answer!

**Comment by Chinese-Coding** [comment]
# Chinese
抱歉, 我没有这个数据集, 所以没有在这个数据集上进行测试. 而且, 目前我不在这个项目上进行研究了, 而且因为只是在暑假作为夏令营项目进行研究的, 所以我也没有计算资源去在这个数据集上进行测试. 恕不能给您具体结果.
同时, 我想提醒你一下, 这个不是原论文作者实现的 [HEAL](https://github.com/yifanlu0227/HEAL), 所以最好不要使用这个仓库里的代码......

# English
Sorry, I don't have this dataset, so I didn't test it on this dataset. Also, I'm not doing research on this project at the moment, and because it's only a summer camp project during the summer, I don't have the computing resources to test it on this dataset. I'm sorry I can't give you specific results.
At the same time, I'd like to remind you that this is not the [HEAL](https://github.com/yifanlu0227/HEAL) implemented by the original paper author, so it's best not to use the code in this repository......

**Comment by ChengchangTian** [comment]
Thank you for your prompt reply, and I also wish you all the best.
